<?php

namespace MinecraftMapEditor\Block;

/**
 * A list of Block IDs and Block Data for all blocks.
 *
 * [blockID, blockData, {optional} class for initialisation}]
 *
 * We could (should?) have keyed each block array with names, but this way it's
 * a smaller file and slightly more legible.
 */
class Names
{
    /** @var array[] Block ID and Data for each block **/
    public static $list = [
        Ref::AIR => 'minecraft:air',

        Ref::STONE             => 'minecraft:stone',
        Ref::GRANITE           => 'minecraft:stone',
        Ref::GRANITE_POLISHED  => 'minecraft:stone',
        Ref::DIORITE           => 'minecraft:stone',
        Ref::DIORITE_POLISHED  => 'minecraft:stone',
        Ref::ANDESITE          => 'minecraft:stone',
        Ref::ANDESITE_POLISHED => 'minecraft:stone',

        Ref::GRASS_BLOCK => 'minecraft:grass',

        Ref::DIRT        => 'minecraft:dirt',
        Ref::DIRT_COARSE => 'minecraft:dirt',
        Ref::PODZOL      => 'minecraft:dirt',

        Ref::COBBLESTONE => 'minecraft:cobblestone',

        Ref::WOOD_PLANK_OAK      => 'minecraft:planks',
        Ref::WOOD_PLANK_SPRUCE   => 'minecraft:planks',
        Ref::WOOD_PLANK_BIRCH    => 'minecraft:planks',
        Ref::WOOD_PLANK_JUNGLE   => 'minecraft:planks',
        Ref::WOOD_PLANK_ACACIA   => 'minecraft:planks',
        Ref::WOOD_PLANK_DARK_OAK => 'minecraft:planks',

        Ref::SAPLING_OAK      => 'minecraft:sapling',
        Ref::SAPLING_SPRUCE   => 'minecraft:sapling',
        Ref::SAPLING_BIRCH    => 'minecraft:sapling',
        Ref::SAPLING_JUNGLE   => 'minecraft:sapling',
        Ref::SAPLING_ACACIA   => 'minecraft:sapling',
        Ref::SAPLING_DARK_OAK => 'minecraft:sapling',

        Ref::BEDROCK       => 'minecraft:bedrock',
        Ref::WATER_FLOWING => 'minecraft:flowing_water',
        Ref::WATER_STILL   => 'minecraft:water',
        Ref::LAVA_FLOWING  => 'minecraft:flowing_lava',
        Ref::LAVA_STILL    => 'minecraft:lava',

        Ref::SAND     => 'minecraft:sand',
        Ref::SAND_RED => 'minecraft:sand',

        Ref::GRAVEL   => 'minecraft:gravel',
        Ref::GOLD_ORE => 'minecraft:gold_ore',
        Ref::IRON_ORE => 'minecraft:iron_ore',
        Ref::COAL_ORE => 'minecraft:coal_ore',

        // Block 17: 4 and 8 specify the orientation
        Ref::WOOD_OAK    => 'minecraft:log',
        Ref::WOOD_SPRUCE => 'minecraft:log',
        Ref::WOOD_BIRCH  => 'minecraft:log',
        Ref::WOOD_JUNGLE => 'minecraft:log',

        // Block 18: 4 and 8 specify decay values
        Ref::LEAVES_OAK    => 'minecraft:leaves',
        Ref::LEAVES_SPRUCE => 'minecraft:leaves',
        Ref::LEAVES_BIRCH  => 'minecraft:leaves',
        Ref::LEAVES_JUNGLE => 'minecraft:leaves',

        Ref::SPONGE     => 'minecraft:sponge',
        Ref::SPONGE_WET => 'minecraft:sponge',

        Ref::GLASS              => 'minecraft:glass',
        Ref::LAPIS_LAZULI_ORE   => 'minecraft:lapis_ore',
        Ref::LAPIS_LAZULI_BLOCK => 'minecraft:lapis_block',
        Ref::DISPENSER          => 'minecraft:dispenser',

        Ref::SANDSTONE          => 'minecraft:sandstone',
        Ref::SANDSTONE_CHISELED => 'minecraft:sandstone',
        Ref::SANDSTONE_SMOOTH   => 'minecraft:sandstone',

        Ref::NOTE_BLOCK    => 'minecraft:noteblock',
        Ref::BED           => 'minecraft:bed',
        Ref::RAIL_POWERED  => 'minecraft:golden_rail',
        Ref::RAIL_DETECTOR => 'minecraft:detector_rail',
        Ref::PISTON_STICKY => 'minecraft:sticky_piston',
        Ref::COBWEB        => 'minecraft:web',

        Ref::DEAD_SHRUB => 'minecraft:tallgrass',
        Ref::GRASS      => 'minecraft:tallgrass',
        Ref::FERN       => 'minecraft:tallgrass',

        Ref::DEAD_BUSH      => 'minecraft:deadbush',
        Ref::PISTON         => 'minecraft:piston',
        Ref::PISTON_HEAD    => 'minecraft:piston_head',
        Ref::WOOL           => 'minecraft:wool',
        Ref::DANDELION      => 'minecraft:yellow_flower',

        Ref::POPPY          => 'minecraft:red_flower',
        Ref::BLUE_ORCHID    => 'minecraft:red_flower',
        Ref::ALLIUM         => 'minecraft:red_flower',
        Ref::AZURE_BLUET    => 'minecraft:red_flower',
        Ref::TULIP_RED      => 'minecraft:red_flower',
        Ref::TULIP_ORANGE   => 'minecraft:red_flower',
        Ref::TULIP_WHITE    => 'minecraft:red_flower',
        Ref::TULIP_PINK     => 'minecraft:red_flower',
        Ref::OXEYE_DAISY    => 'minecraft:red_flower',

        Ref::MUSHROOM_BROWN => 'minecraft:brown_mushroom',
        Ref::MUSHROOM_RED   => 'minecraft:red_mushroom',
        Ref::GOLD_BLOCK     => 'minecraft:gold_block',
        Ref::IRON_BLOCK     => 'minecraft:iron_block',

        Ref::DOUBLE_SLAB_STONE        => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_SANDSTONE    => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_STONE_WOOD   => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_COBBLESTONE  => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_BRICK        => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_STONE_BRICK  => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_NETHER_BRICK => 'minecraft:double_stone_slab',
        Ref::DOUBLE_SLAB_QUARTZ       => 'minecraft:double_stone_slab',

        Ref::SLAB_STONE        => 'minecraft:stone_slab',
        Ref::SLAB_SANDSTONE    => 'minecraft:stone_slab',
        Ref::SLAB_STONE_WOOD   => 'minecraft:stone_slab',
        Ref::SLAB_COBBLESTONE  => 'minecraft:stone_slab',
        Ref::SLAB_BRICK        => 'minecraft:stone_slab',
        Ref::SLAB_STONE_BRICK  => 'minecraft:stone_slab',
        Ref::SLAB_NETHER_BRICK => 'minecraft:stone_slab',
        Ref::SLAB_QUARTZ       => 'minecraft:stone_slab',

        Ref::BRICKS                => 'minecraft:brick_block',
        Ref::TNT                   => 'minecraft:tnt',
        Ref::BOOKSHELF             => 'minecraft:bookshelf',
        Ref::COBBLESTONE_MOSSY     => 'minecraft:mossy_cobblestone',
        Ref::OBSIDIAN              => 'minecraft:obsidian',
        Ref::TORCH                 => 'minecraft:torch',
        Ref::FIRE                  => 'minecraft:fire',
        Ref::MOB_SPAWNER           => 'minecraft:mob_spawner',
        Ref::STAIRS_WOOD_OAK       => 'minecraft:oak_stairs',
        Ref::CHEST                 => 'minecraft:chest',
        Ref::REDSTONE_WIRE         => 'minecraft:redstone_wire',
        Ref::DIAMOND_ORE           => 'minecraft:diamond_ore',
        Ref::DIAMOND_BLOCK         => 'minecraft:diamond_block',
        Ref::CRAFTING_TABLE        => 'minecraft:crafting_table',
        Ref::WHEAT                 => 'minecraft:wheat',
        Ref::FARMLAND              => 'minecraft:farmland',
        Ref::FURNACE               => 'minecraft:furnace',
        Ref::FURNACE_BURNING       => 'minecraft:lit_furnace',
        Ref::SIGN_STANDING         => 'minecraft:standing_sign',
        Ref::DOOR_WOOD_OAK         => 'minecraft:wooden_door',
        Ref::LADDER                => 'minecraft:ladder',
        Ref::RAIL                  => 'minecraft:rail',
        Ref::STAIRS_COBBLESTONE    => 'minecraft:stone_stairs',
        Ref::SIGN_WALL             => 'minecraft:wall_sign',
        Ref::LEVER                 => 'minecraft:lever',
        Ref::PRESSURE_PLATE_STONE  => 'minecraft:stone_pressure_plate',
        Ref::DOOR_IRON             => 'minecraft:iron_door',
        Ref::PRESSURE_PLATE_WOOD   => 'minecraft:wooden_pressure_plate',
        Ref::REDSTONE_ORE          => 'minecraft:redstone_ore',
        Ref::REDSTONE_ORE_GLOWING  => 'minecraft:lit_redstone_ore',
        Ref::REDSTONE_TORCH_OFF    => 'minecraft:unlit_redstone_torch',
        Ref::REDSTONE_TORCH_ON     => 'minecraft:redstone_torch',
        Ref::BUTTON_STONE          => 'minecraft:stone_button',
        Ref::SNOW_LAYER            => 'minecraft:snow_layer',
        Ref::ICE                   => 'minecraft:ice',
        Ref::SNOW_BLOCK            => 'minecraft:snow',
        Ref::CACTUS                => 'minecraft:cactus',
        Ref::CLAY                  => 'minecraft:clay',
        Ref::SUGAR_CANE            => 'minecraft:reeds',
        Ref::JUKEBOX               => 'minecraft:jukebox',
        Ref::FENCE_OAK             => 'minecraft:fence',
        Ref::PUMPKIN               => 'minecraft:pumpkin',
        Ref::NETHERRACK            => 'minecraft:netherrack',
        Ref::SAND_SOUL             => 'minecraft:soul_sand',
        Ref::GLOWSTONE             => 'minecraft:glowstone',
        Ref::NETHER_PORTAL         => 'minecraft:portal',
        Ref::JACK_O_LANTERN        => 'minecraft:lit_pumpkin',
        Ref::CAKE                  => 'minecraft:cake',
        Ref::REDSTONE_REPEATER_OFF => 'minecraft:unpowered_repeater',
        Ref::REDSTONE_REPEATER_ON  => 'minecraft:powered_repeater',
        Ref::GLASS_STAINED         => 'minecraft:stained_glass',
        Ref::TRAPDOOR_WOODEN       => 'minecraft:trapdoor',

        Ref::MONSTER_EGG_STONE                => 'minecraft:monster_egg',
        Ref::MONSTER_EGG_COBBLESTONE          => 'minecraft:monster_egg',
        Ref::MONSTER_EGG_STONE_BRICK          => 'minecraft:monster_egg',
        Ref::MONSTER_EGG_STONE_BRICK_MOSSY    => 'minecraft:monster_egg',
        Ref::MONSTER_EGG_STONE_BRICK_CRACKED  => 'minecraft:monster_egg',
        Ref::MONSTER_EGG_STONE_BRICK_CHISELED => 'minecraft:monster_egg',

        Ref::STONE_BRICKS          => 'minecraft:stonebrick',
        Ref::STONE_BRICKS_MOSSY    => 'minecraft:stonebrick',
        Ref::STONE_BRICKS_CRACKED  => 'minecraft:stonebrick',
        Ref::STONE_BRICKS_CHISELED => 'minecraft:stonebrick',

        Ref::MUSHROOM_BLOCK_BROWN => 'minecraft:brown_mushroom_block',
        Ref::MUSHROOM_BLOCK_RED   => 'minecraft:red_mushroom_block',
        Ref::IRON_BARS            => 'minecraft:iron_bars',
        Ref::GLASS_PANE           => 'minecraft:glass_pane',
        Ref::MELON                => 'minecraft:melon_block',
        Ref::STEM_PUMPKIN         => 'minecraft:pumpkin_stem',
        Ref::STEM_MELON           => 'minecraft:melon_stem',
        Ref::VINES                => 'minecraft:vine',
        Ref::FENCE_GATE_OAK       => 'minecraft:fence_gate',
        Ref::STAIRS_BRICK         => 'minecraft:brick_stairs',
        Ref::STAIRS_STONE_BRICK   => 'minecraft:stone_brick_stairs',
        Ref::MYCELIUM             => 'minecraft:mycelium',
        Ref::LILY_PAD             => 'minecraft:waterlily',
        Ref::NETHER_BRICK         => 'minecraft:nether_brick',
        Ref::FENCE_NETHER_BRICK   => 'minecraft:nether_brick_fence',
        Ref::STAIRS_NETHER_BRICK  => 'minecraft:nether_brick_stairs',
        Ref::NETHER_WART          => 'minecraft:nether_wart',
        Ref::ENCHANTMENT_TABLE    => 'minecraft:enchanting_table',
        Ref::BREWING_STAND        => 'minecraft:brewing_stand',
        Ref::CAULDRON             => 'minecraft:cauldron',
        Ref::END_PORTAL           => 'minecraft:end_portal',
        Ref::END_PORTAL_FRAME     => 'minecraft:end_portal_frame',
        Ref::END_STONE            => 'minecraft:end_stone',
        Ref::DRAGON_EGG           => 'minecraft:dragon_egg',
        Ref::REDSTONE_LAMP_OFF    => 'minecraft:redstone_lamp',
        Ref::REDSTONE_LAMP_ON     => 'minecraft:lit_redstone_lamp',

        Ref::DOUBLE_SLAB_WOOD_OAK      => 'minecraft:double_wooden_slab',
        Ref::DOUBLE_SLAB_WOOD_SPRUCE   => 'minecraft:double_wooden_slab',
        Ref::DOUBLE_SLAB_WOOD_BIRCH    => 'minecraft:double_wooden_slab',
        Ref::DOUBLE_SLAB_WOOD_JUNGLE   => 'minecraft:double_wooden_slab',
        Ref::DOUBLE_SLAB_WOOD_ACACIA   => 'minecraft:double_wooden_slab',
        Ref::DOUBLE_SLAB_WOOD_DARK_OAK => 'minecraft:double_wooden_slab',

        Ref::SLAB_WOOD_OAK      => 'minecraft:wooden_slab',
        Ref::SLAB_WOOD_SPRUCE   => 'minecraft:wooden_slab',
        Ref::SLAB_WOOD_BIRCH    => 'minecraft:wooden_slab',
        Ref::SLAB_WOOD_JUNGLE   => 'minecraft:wooden_slab',
        Ref::SLAB_WOOD_ACACIA   => 'minecraft:wooden_slab',
        Ref::SLAB_WOOD_DARK_OAK => 'minecraft:wooden_slab',

        Ref::COCOA              => 'minecraft:cocoa',
        Ref::STAIRS_SANDSTONE   => 'minecraft:sandstone_stairs',
        Ref::EMERALD_ORE        => 'minecraft:emerald_ore',
        Ref::CHEST_ENDER        => 'minecraft:ender_chest',
        Ref::TRIPWIRE_HOOK      => 'minecraft:tripwire_hook',
        Ref::TRIPWIRE           => 'minecraft:tripwire',
        Ref::EMERALD_BLOCK      => 'minecraft:emerald_block',
        Ref::STAIRS_WOOD_SPRUCE => 'minecraft:spruce_stairs',
        Ref::STAIRS_WOOD_BIRCH  => 'minecraft:birch_stairs',
        Ref::STAIRS_WOOD_JUNGLE => 'minecraft:jungle_stairs',
        Ref::COMMAND_BLOCK      => 'minecraft:command_block',
        Ref::BEACON             => 'minecraft:beacon',

        Ref::COBBLESTONE_WALL       => 'minecraft:cobblestone_wall',
        Ref::COBBLESTONE_WALL_MOSSY => 'minecraft:cobblestone_wall',

        Ref::FLOWER_POT                    => 'minecraft:flower_pot',
        Ref::CARROTS                       => 'minecraft:carrots',
        Ref::POTATOES                      => 'minecraft:potatoes',
        Ref::BUTTON_WOODEN                 => 'minecraft:wooden_button',
        Ref::MOB_HEAD                      => 'minecraft:skull',
        Ref::ANVIL                         => 'minecraft:anvil',
        Ref::CHEST_TRAPPED                 => 'minecraft:trapped_chest',
        Ref::PRESSURE_PLATE_WEIGHTED_LIGHT => 'minecraft:light_weighted_pressure_plate',
        Ref::PRESSURE_PLATE_WEIGHTED_HEAVY => 'minecraft:heavy_weighted_pressure_plate',
        Ref::REDSTONE_COMPARATOR           => 'minecraft:unpowered_comparator',
        Ref::DAYLIGHT_SENSOR               => 'minecraft:powered_comparator',
        Ref::REDSTONE_BLOCK                => 'minecraft:daylight_detector',
        Ref::NETHER_QUARTZ_ORE             => 'minecraft:quartz_ore',
        Ref::HOPPER                        => 'minecraft:hopper',

        Ref::QUARTZ_BLOCK          => 'minecraft:quartz_block',
        Ref::QUARTZ_BLOCK_CHISELED => 'minecraft:quartz_block',
        Ref::QUARTZ_BLOCK_PILLAR   => 'minecraft:quartz_block',

        Ref::STAIRS_QUARTZ      => 'minecraft:quartz_stairs',
        Ref::RAIL_ACTIVATOR     => 'minecraft:activator_rail',
        Ref::DROPPER            => 'minecraft:dropper',
        Ref::CLAY_STAINED       => 'minecraft:stained_hardened_clay',
        Ref::GLASS_PANE_STAINED => 'minecraft:stained_glass_pane',

        Ref::LEAVES_ACACIA   => 'minecraft:leaves2',
        Ref::LEAVES_DARK_OAK => 'minecraft:leaves2',

        Ref::WOOD_ACACIA   => 'minecraft:log2',
        Ref::WOOD_DARK_OAK => 'minecraft:log2',

        Ref::STAIRS_WOOD_ACACIA   => 'minecraft:acacia_stairs',
        Ref::STAIRS_WOOD_DARK_OAK => 'minecraft:dark_oak_stairs',
        Ref::SLIME_BLOCK          => 'minecraft:slime',
        Ref::BARRIER              => 'minecraft:barrier',
        Ref::TRAPDOOR_IRON        => 'minecraft:iron_trapdoor',

        Ref::PRISMARINE        => 'minecraft:prismarine',
        Ref::PRISMARINE_BRICKS => 'minecraft:prismarine',
        Ref::PRISMARINE_DARK   => 'minecraft:prismarine',

        Ref::SEA_LANTERN => 'minecraft:sea_lantern',
        Ref::HAY_BALE    => 'minecraft:hay_block',

        Ref::CARPET => 'minecraft:carpet',

        Ref::CLAY_HARDENED => 'minecraft:hardened_clay',
        Ref::COAL_BLOCK    => 'minecraft:coal_block',
        Ref::ICE_PACKED    => 'minecraft:packed_ice',

        Ref::SUNFLOWER         => 'minecraft:double_plant',
        Ref::LILAC             => 'minecraft:double_plant',
        Ref::GRASS_DOUBLE_TALL => 'minecraft:double_plant',
        Ref::FERN_LARGE        => 'minecraft:double_plant',
        Ref::ROSE_BUSH         => 'minecraft:double_plant',
        Ref::PEONY             => 'minecraft:double_plant',

        Ref::BANNER_STANDING          => 'minecraft:standing_banner',
        Ref::BANNER_WALL              => 'minecraft:wall_banner',
        Ref::DAYLIGHT_SENSOR_INVERTED => 'minecraft:daylight_detector_inverted',

        Ref::SANDSTONE_RED          => 'minecraft:red_sandstone',
        Ref::SANDSTONE_RED_CHISELED => 'minecraft:red_sandstone',
        Ref::SANDSTONE_RED_SMOOTH   => 'minecraft:red_sandstone',

        Ref::STAIRS_SANDSTONE_RED      => 'minecraft:red_sandstone_stairs',
        Ref::DOUBLE_SLAB_SANDSTONE_RED => 'minecraft:double_stone_slab2',
        Ref::SLAB_SANDSTONE_RED        => 'minecraft:stone_slab2',
        Ref::FENCE_GATE_SPRUCE         => 'minecraft:spruce_fence_gate',
        Ref::FENCE_GATE_BIRCH          => 'minecraft:birch_fence_gate',
        Ref::FENCE_GATE_JUNGLE         => 'minecraft:jungle_fence_gate',
        Ref::FENCE_GATE_DARK_OAK       => 'minecraft:dark_oak_fence_gate',
        Ref::FENCE_GATE_ACACIA         => 'minecraft:acacia_fence_gate',
        Ref::FENCE_SPRUCE              => 'minecraft:spruce_fence',
        Ref::FENCE_BIRCH               => 'minecraft:birch_fence',
        Ref::FENCE_JUNGLE              => 'minecraft:jungle_fence',
        Ref::FENCE_DARK_OAK            => 'minecraft:dark_oak_fence',
        Ref::FENCE_ACACIA              => 'minecraft:acacia_fence',
        Ref::DOOR_SPRUCE               => 'minecraft:spruce_door',
        Ref::DOOR_BIRCH                => 'minecraft:birch_door',
        Ref::DOOR_JUNGLE               => 'minecraft:jungle_door',
        Ref::DOOR_DARK_OAK             => 'minecraft:dark_oak_door',
        Ref::DOOR_ACACIA               => 'minecraft:acacia_door',
    ];
}
